spring.application.name=shopping
server.port=9000
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.datasource.url=jdbc:mysql://10.250.11.240:3306/coffee?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=My@Sql01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.profiles.active=windows
#spring.profiles.active=linux
#how to apply method 
#java -jar myapp.jar --spring.profiles.active=linux
# Force UTF-8 encoding for the server
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Spring MVC default charset
spring.mvc.charset=UTF-8

# HTTP encoding settings
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8

# SQL script encoding (if needed)
spring.datasource.sql-script-encoding=UTF-8